### PR TITLE
Making PDAF compilation less machine-specific

### PR DESCRIPTION
**Pull request by jjokella**
I have tried to use CMake-generated variables for the library / include paths used in PDAF compilation.

Compilation of `eCLM-ParFlow-PDAF` works with PDAF branch https://github.com/HPSCTerrSys/pdaf/tree/tsmp-pdaf-patched-dev.

Most notably, I have included a `find_package` for the MKL.

https://github.com/HPSCTerrSys/eTSMP/blob/d20c2e7c65f0ed2ee93925264209759b4ed7f0c2/cmake/BuildPDAF.cmake#L11-L20

@kvrigor: Would be nice if you could look over this. However, this should be merged after our main PR https://github.com/HPSCTerrSys/eTSMP/pull/9, of course! I started these `dev` branches for not breaking the build in the main PR like I accidentally did yesterday.

### CODE REVIEW

**Comment by kvrigor** [comment]
We always strive for generality in our build scripts so this change is in a good direction 😁. Firstly you can `rebase` this branch with `master` so we only see the relevant changes in the diffs.

I'm not familiar with the linking mechanisms of MKL. Is `MKL_LINK` an environment variable that influences MKL linker flags in `PDAF`?

**Comment by jjokella** [comment]
1) I am sadly not a big "rebaser", so I did a "merge"... Now the commits are not good, but at least the differences are correct and the commits can then be discarded after a Squashed-Merge of the PR, if you are fine with that!?

2) I am not 100% sure about `MKL_LINK`. It was generated by the `find_package` (found it in the `CMakeCache.txt`
 https://github.com/HPSCTerrSys/eTSMP/blob/8264768d911df67f85c58e4650a7116040bb2387/cmake/BuildPDAF.cmake#L13
I just tried around with it, if I could get the MKL-variables used later to contain static libraries and found out that it takes the additional `unset` command. This is all knowledge built up today, no deeper insights.

**Comment by kvrigor** [comment]
> I am sadly not a big "rebaser", so I did a "merge"... Now the commits are not good, but at least the differences are correct and the commits can then be discarded after a Squashed-Merge of the PR, if you are fine with that!?

Sure! Branch commits doesn't really bother me--more importantly, we should only see the changed files in the PR.

Other than that, the changes LGTM! I'll leave it up to you to **squash-merge** the PR 😉 . Let's try to follow this commit style for merge commits (e.g. see last [3 commits](https://github.com/HPSCTerrSys/eTSMP/commits/master)):

```
Summary of PR (#PR_NUMBER)

<optional commit message>
```

**Comment by jjokella** [comment]
Perfect, when I get the time to clean things up, I will do the squash merge.

Regarding commit-style, I completely agree. Actually I particularly liked the style of https://github.com/HPSCTerrSys/eTSMP/commit/fd501af8bd34e27b474ee56b99b9aec91fd04361 with the key commits. If you used some automation for that I would be very interested! Especially the single commits being there as links is very convenient.

**Comment by jjokella** [comment]
@kvrigor  I am currently not authorized to merge the PR. Can you give me the permission?

**Comment by kvrigor** [comment]
@jjokella please retry

**Pull request merged**
