### PR TITLE
CMake build script for TSMP-PDAF

### PR DESCRIPTION
**Pull request by jjokella**
Goal of this PR is writing a CMake script for TSMP-PDAF that works in the CMake framework set up in the eTSMP repository.

Current status: A minimized Bash build script can compile CLM35-ParFlow-PDAF after the component models have been compiled using CMake in eTSMP.

### CODE REVIEW

**Comment by jjokella** [comment]
Hey @kvrigor  thanks a lot for the great template `BuildPDAF.cmake`! I started from this and was now able to build the formerly Bash-script built PDAF versions with CMake.

I changed the format a little bit, using three seperate CMake files (maybe this fits the modular structure of CMake). 

More things will be developed in the future, and I still have the problem with the duplicate `-lmct` that I will write an issue about, but in general from my side this can be merged!

**Comment by jjokella** [comment]
I added a small change after merging PDAF-patches for OASIS under a cpp-definition.

**Comment by kvrigor** [comment]
Looks good @jjokella ! I did a couple of minor improvements. Could you also test in your side if the build still works? Some comments:

- `${CMAKE_INSTALL_PREFIX}` should be used instead of `${BUILD_DIR}` for referencing the header files and
the libraries since `${BUILD_DIR}` is a temporary folder that can be deleted after the `cmake --install` step. This is already fixed.
- Does the PDAF build generate an executable? If so, after the install step it should be visible under `${CMAKE_INSTALL_PREFIX}/bin`. If it doesn't appear, then the executable may need to be manually installed like how it's done in `BuildCOSMO.cmake`:

https://github.com/HPSCTerrSys/eTSMP/blob/d1eddfed78ce0ee72698107234a5285014c3d7ca/cmake/BuildCOSMO.cmake#L33-L36

**Comment by jjokella** [comment]
The PDAF-Framework project generates an executable `${CMAKE_INSTALL_PREFIX}/bin/tsmp-pdaf`. I guess, this can be done in a nicer CMake-way, though.

I have slightly changed giving the `USE_PDAF` to eCLM, in particular I have moved this out of the OASIS nested condition.

**Comment by kvrigor** [comment]
> The PDAF-Framework project generates an executable ${CMAKE_INSTALL_PREFIX}/bin/tsmp-pdaf. I guess, this can be done in a nicer CMake-way, though.

That's already perfect! The model's native build system is supposed to properly install its artifacts to the right locations. What we did for `COSMO` is actually a workaround 😅

**Comment by jjokella** [comment]
> Looks good @jjokella ! I did a couple of minor improvements. Could you also test in your side if the build still works? 

I ran the tests on JURECA and had to re-introduce some of the ugly path-setting. I tried to document the files that were missing.

Now, I am back at the point that everything compiles, except the "Duplicate `-lmct` Issue" for `eCLM-ParFlow-PDAF`. When I fix this by hand and only run the last linker command, then I can also compile `eCLM-ParFlow-PDAF`.

**Comment by kvrigor** [comment]
> I ran the tests on JURECA and had to re-introduce some of the ugly path-setting. I tried to document the files that were missing.

You may have to update your CLM3.5 up to commit https://github.com/HPSCTerrSys/CLM3.5/commit/5c8bf739b9eb441b82bac4f0455b06f2f46c0555. This fix installs all header files to `${CMAKE_INSTALL_PREFIX}/include/clm3.5`.

> When I fix this by hand and only run the last linker command

Can you share the exact commands so I could also replicate them? :)

**Comment by jjokella** [comment]
## CLM3.5-ParFlow-PDAF
> You may have to update your CLM3.5 up to commit [HPSCTerrSys/CLM3.5@5c8bf73](https://github.com/HPSCTerrSys/CLM3.5/commit/5c8bf739b9eb441b82bac4f0455b06f2f46c0555). This fix installs all header files to `${CMAKE_INSTALL_PREFIX}/include/clm3.5`.

In my tests with CLM3.5,  `${CMAKE_INSTALL_PREFIX}/include/clm3.5` contains object files (`*.o`). 

For CLM3.5-PDAF this was fine.

For CLM3.5-ParFlow-PDAF and the compilation is asking me for  ParFlow-related header files like `amps_common.h` and `parflow_config.h`. I have added these two by hand, but not yet committed it, because there was still an error left in CLM3.5-ParFlow-PDAF compilation, when I finished yesterday.

## eCLM-ParFlow-PDAF
> > When I fix this by hand and only run the last linker command
> 
> Can you share the exact commands so I could also replicate them? :)

The whole command is very long. Easiest replication should be running the `README` for eCLM-Parflow-PDAF, then finally running the build command with `-v` option. Then, the last command before the error can be copied from command line output, the eCLM `-lmct` has to be changed to `-lmct2`.

Summary of commands
```
# README commands until build step

# Build step, verbose
cmake --build ${BUILD_DIR} -v

# Rename eCLM-generated `libmct.a` to `libmct2.a`
mv ${CMAKE_INSTALL_PREFIX}/lib/libmct.a ${CMAKE_INSTALL_PREFIX}/lib/libmct2.a

# Move into compile directory
cd ${PDAF_SRC}/interface/framework

# Run copied and manipulated linking command for PDAF-Framework
#  (the pasted command is my command with specific paths replaced by the corresponding environment variables)
#  Notice: `-lmct2` in eCLM library section
${EBROOTPSMPI}/bin/mpif90 -O2 -xHost -r8 -o ${CMAKE_INSTALL_PREFIX}/bin/tsmp-pdaf mod_parallel_model.o mod_tsmp.o mod_parallel_pdaf.o mod_assimilation.o parser_mpi.o mod_read_obs.o pdaf_terrsysmp.o integrate_pdaf.o init_parallel_pdaf.o finalize_pdaf.o init_pdaf.o init_pdaf_parse.o init_pdaf_info.o assimilate_pdaf.o init_ens.o prepoststep_ens_pdaf.o next_observation_pdaf.o distribute_state_pdaf.o collect_state_pdaf.o init_obs_pdaf.o init_dim_obs_pdaf.o obs_op_pdaf.o prodrinva_pdaf.o init_obsvar_pdaf.o add_obs_error_pdaf.o init_obscovar_pdaf.o init_n_domains_pdaf.o init_dim_l_pdaf.o g2l_state_pdaf.o l2g_state_pdaf.o prodrinva_l_pdaf.o init_obs_l_pdaf.o init_dim_obs_l_pdaf.o g2l_obs_pdaf.o init_obsvar_l_pdaf.o init_dim_obs_f_pdaf.o init_obs_f_pdaf.o obs_op_f_pdaf.o localize_covar_pdaf.o -L${PDAF_SRC}/lib -lpdaf-d -Wl,--start-group ${EBROOTIMKL}/mkl/latest/lib/intel64/libmkl_intel_lp64.a ${EBROOTIMKL}/mkl/latest/lib/intel64/libmkl_intel_thread.a ${EBROOTIMKL}/mkl/latest/lib/intel64/libmkl_core.a -L${EBROOTPSMPI}/lib64 -Wl,--end-group -qopenmp -lpthread -lm ${CMAKE_INSTALL_PREFIX}/lib/libmodel.a -L${CMAKE_INSTALL_PREFIX}/lib -L${EBROOTPSMPI}/lib -lmpich -L${EBROOTNETCDF}/lib64 -L${EBROOTNETCDFMINFORTRAN}/lib -lnetcdff -lnetcdf -L${CMAKE_INSTALL_PREFIX}/lib -leclm -lclm -ldatm -lglc -lgptl -lice -lmosart -locn -lpio -lwav -lesp -lmct2 -lmpeu -lpnetcdf -qmkl -lcsm_share -L${CMAKE_INSTALL_PREFIX}/OASIS3-MCT/lib -lpsmile.MPI1 -lmct -lmpeu -lscrip -L${CMAKE_INSTALL_PREFIX}/lib -lpfsimulator -lamps -lpfkinsol -lgfortran -lcjson -L${EBROOTHYPRE}/lib -lHYPRE -L/lib64 -lslurm

```

**Comment by kvrigor** [comment]
> In my tests with CLM3.5, `${CMAKE_INSTALL_PREFIX}/include/clm3.5` contains object files (`*.o`).

My bad! Already fixed in https://github.com/HPSCTerrSys/CLM3.5/commit/6301079b68e08297a5eb7814bc90ad4f39e770c6. PDAF should now be able to include from `${CMAKE_INSTALL_PREFIX}/include/clm3.5`.

> For CLM3.5-ParFlow-PDAF and the compilation is asking me for ParFlow-related header files like amps_common.h and parflow_config.h.

Assuming you have this [fix](https://github.com/HPSCTerrSys/parflow/commit/3aefeff7ad970a74d9ac91ae949ace0e900ea4e2), all ParFlow header files should be under `${CMAKE_INSTALL_PREFIX}/include/parflow`:

```bash
$ ls ${INSTALL_DIR}/include/parflow
amps_common.h      f2c.h                index_space.h         parflow_config.h     pf_omploops.h
amps.h             fgetopt.h            info_header.h         parflow.h            pfversion.h
amps_proto.h       file_versions.h      input_database.h      parflow_netcdf.h     problem_bc.h
backend_mapping.h  general.h            kinsol_dependences.h  parflow_proto_f90.h  problem_eval.h
background.h       geometry.h           lb.h                  parflow_proto_f.h    problem.h
bc_pressure.h      geostats.h           llnlmath.h            parflow_proto.h      region.h
char_vector.h      globals.h            llnltyps.h            pf_cudaloops.h       solver.h
clustering.h       grgeometry.h         logging.h             pf_cudamalloc.h      time_cycle_data.h
communication.h    grgeom_list.h        loops.h               pf_devices.h         timing.h
computation.h      grgeom_octree.h      matrix.h              pf_hypre.h           vector.h
drv_gridmodule.h   grid.h               metadata.h            pf_kokkosloops.h     well.h
drv_module.h       hbt.h                nl_function_eval.h    pf_kokkosmalloc.h
drv_tilemodule.h   hypre_dependences.h  n_vector.h            pf_module.h
```

**Comment by kvrigor** [comment]
Hey @jjokella we're almost there! We can merge this PR after we nail these three things:

- [ ] All `include` and `linker` paths passed to PDAF should reference solely from `${CMAKE_INSTALL_PREFIX}`.  We strive to package the built component models into a single install folder (i.e. `${CMAKE_INSTALL_PREFIX}` ), which means all model binaries and its dependencies should live inside this folder.
  - `eCLM` should now be fine, but `CLM3.5` and `ParFlow` still declares paths outside `${CMAKE_INSTALL_PREFIX}`.
  - If there are still missing `include` files, we need to fix them at the component model side.
- [ ] `CLM3.5-ParFlow-PDAF` build should work
- [ ] `eCLM-ParFlow-PDAF` build should work (`libmct.a` is now [automatically renamed](https://github.com/HPSCTerrSys/eTSMP/blob/f3363824b3fe7682c7d3554a67110fa2d85cf62b/cmake/BuildeCLM.cmake#L43-L51) after eCLM installation )

**Comment by jjokella** [comment]
Hey @kvrigor  thanks for your changes! We really are getting close. After my tests, we have three unwanted include paths left:

eCLM:
https://github.com/HPSCTerrSys/eTSMP/blob/dfc8ac037f9b07ef6f844ae11294cbabf284e675/cmake/BuildPDAFMODEL.cmake#L36-L37

ParFlow:
https://github.com/HPSCTerrSys/eTSMP/blob/dfc8ac037f9b07ef6f844ae11294cbabf284e675/cmake/BuildPDAFMODEL.cmake#L43

**Comment by kvrigor** [comment]
> EDIT: for the Parflow-side, I have introduced a proposed fix: https://github.com/HPSCTerrSys/parflow/commit/0ce06f95136b4e6615c7331eb2e8c60fb12e9db6

I think our commit are clashing: this should have been fixed at https://github.com/HPSCTerrSys/parflow/commit/dbeda10622f0abaa9b2690f1304832b474ab30f2, but I don't see this anymore after your commit. Can you help to fix this?

**Comment by jjokella** [comment]
> > EDIT: for the Parflow-side, I have introduced a proposed fix: [HPSCTerrSys/parflow@0ce06f9](https://github.com/HPSCTerrSys/parflow/commit/0ce06f95136b4e6615c7331eb2e8c60fb12e9db6)
> 
> I think our commits are clashing: this should have been fixed at [HPSCTerrSys/parflow@dbeda10](https://github.com/HPSCTerrSys/parflow/commit/dbeda10622f0abaa9b2690f1304832b474ab30f2), but I don't see this anymore after your commit. Can you help to fix this?

You entered the commit in the `master` and I merged it into the branch `tsmp-pdaf`. In this branch, both changes are inside: https://github.com/HPSCTerrSys/parflow/blob/tsmp-pdaf/pfsimulator/amps/CMakeLists.txt

Hm, in my test, adding the files to `HEADER_FILES` did not help. Maybe the files are added after the `install` command in `pfsimulator/parflow_lib/CMakeLists.txt` is executed?

Anyway, I will also do a test without my change inside.

**Comment by kvrigor** [comment]
`CLM3.5-ParFlow-PDAF` works! However I get an error for `eCLM-ParFlow-PDAF`:

```sh
../make.arch/linux_ifort.h:18: *** Recursive variable 'CC' references itself (eventually).  Stop.
gmake[2]: *** [CMakeFiles/PDAF.dir/build.make:86: PDAF/src/PDAF-stamp/PDAF-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/PDAF.dir/all] Error 2
```

**Comment by jjokella** [comment]
> `CLM3.5-ParFlow-PDAF` works! However I get an error for `eCLM-ParFlow-PDAF`:

Yes that was me being overly eager to start making the PDAF compilation less environment-specific by changing PDAF's own Makefile(-header) in order to use the compilers specified by the envvars `FC` and `CC` set from the scripts in `eTSMP/env`.

With the newest version of PDAF, this should be fixed (by commenting out setting `FC` in the Makefile-header).

**Comment by kvrigor** [comment]
eCLM-PDAF now works 👍🏽. `eCLM/devel-pdaf` has now been merged to `eCLM/master`. The `README` needs to be updated so that it points to the default `eCLM` branch. I'll test the eCLM-PDAF build once more; this time with `eCLM/master`.

@jjokella feel free to do final cleanups/edits as you wish. Once you give me the green light I will merge this PR.

**Pull request merged**
